SELECT * FROM MARATONA_HOMENS
SELECT * FROM MARATONA_MULHERES

SELECT DISTINCT
MH.Country AS PAIS_HOMENS,
MM.Country AS PAIS_MULHERES
FROM
MARATONA_HOMENS MH
FULL JOIN
MARATONA_MULHERES MM
ON MH.Country = MM.Country

CREATE VIEW VENCEDORES_POR_PAIS_HOMENS AS

SELECT Country AS PAIS, COUNT(Country) AS TOTAL_VENCEDORES_HOMENS
FROM MARATONA_HOMENS
GROUP BY Country
ORDER BY TOTAL_VENCEDORES_HOMENS DESC

CREATE VIEW VENCEDORAS_POR_PAIS_MULHERES AS

SELECT Country AS PAIS, COUNT(Country) AS TOTAL_VENCEDORAS_MULHERES 
FROM MARATONA_MULHERES
WHERE Country IS NOT NULL
GROUP BY Country 
ORDER BY TOTAL_VENCEDORAS_MULHERES DESC

SELECT * FROM VENCEDORAS_POR_PAIS_MULHERES
SELECT * FROM VENCEDORES_POR_PAIS_HOMENS

SELECT COUNT(MH.[Winner]) AS TOTAL_MARATONAS_HOMENS, ROUND(SUM(MH.[Distance (KM)]) / COUNT(MH.[Winner]), 2) AS MEDIA_KM_HOMENS,
COUNT(MM.Winner) AS TOTAL_MARATONAS_MULHERES, ROUND(SUM(MM.[Distance (KM)]) / COUNT(MM.[Winner]), 2) AS MEDIA_KM_MULHERES
FROM MARATONA_HOMENS MH
INNER JOIN MARATONA_MULHERES MM ON MH.[Year] = MM.[Year]


